name: Hello World file

on:
  repository_dispatch:
    types: [opened]
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "John Dohoney"
