name: Hello World file

on:
  repository_dispatch:
    types: [api-invoke]
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "John Dohoney"
      - run: 'echo "field: ${{ github.event.client_payload.foo }}"'
